name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # Передаются в билд из GitHub Secrets
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # В проекте используется OpenTelemetry и во время билда ищется пакет exporter-jaeger.
      # Ставим его без сохранения в package.json, чтобы билд в CI не падал.
      - name: Ensure Jaeger exporter is available
        run: npm install --no-save @opentelemetry/exporter-jaeger

      - name: Build Next.js
        run: npm run build

      - name: Export static site
        run: npx next export -o out

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        # Замените binage-lite на ID вашего проекта в Firebase, если он другой
        run: firebase deploy --only hosting --project binage-lite
