name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting deployment..."

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Verify required env
        run: |
          [ -n "$NEXT_PUBLIC_SUPABASE_URL" ] || { echo "NEXT_PUBLIC_SUPABASE_URL is missing"; exit 1; }
          [ -n "$NEXT_PUBLIC_SUPABASE_ANON_KEY" ] || { echo "NEXT_PUBLIC_SUPABASE_ANON_KEY is missing"; exit 1; }

      - name: Build Next.js
        run: npm run build

      - name: Export static site
        run: npx next export --outdir=out

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }}

      - name: Post Setup Node.js
        run: echo "Post Node.js setup"

      - name: Post Checkout
        run: echo "Post checkout"

      - name: Complete job
        run: echo "Deployment completed successfully!"
