name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Общие переменные окружения для всех шагов
    env:
      # берём из GitHub → Settings → Secrets and variables → Actions
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify required env
        run: |
          [ -n "$NEXT_PUBLIC_SUPABASE_URL" ] || { echo "NEXT_PUBLIC_SUPABASE_URL is missing"; exit 1; }
          [ -n "$NEXT_PUBLIC_SUPABASE_ANON_KEY" ] || { echo "NEXT_PUBLIC_SUPABASE_ANON_KEY is missing"; exit 1; }

      - name: Build Next.js
        run: npm run build

      # Если у тебя SSG/статический экспорт — оставь этот шаг.
      # Если у тебя чистый SSR — этот шаг удали, а деплой делай как статические ассеты build не получится.
      - name: Export static site
        run: npx next export -o out

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy to Firebase Hosting
        # Если у тебя проект Firebase называется иначе — поменяй id после --project
        run: firebase deploy --only hosting --project binage-lite
