name: Deploy to Firebase Hosting (SSR)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build (Next.js)
        run: npm run build

      # Пишем JSON ключ во временный файл и прокидываем путь в env
      - name: Configure GCP credentials for Firebase CLI
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > "${RUNNER_TEMP}/gcp.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=${RUNNER_TEMP}/gcp.json" >> "$GITHUB_ENV"

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Enable Firebase webframeworks (once ok if enabled)
        run: npx firebase experiments:enable webframeworks

      - name: Deploy to Firebase Hosting (SSR)
        run: |
          npx firebase deploy \
            --only hosting \
            --project "${{ secrets.FIREBASE_PROJECT_ID }}"
