name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build (Next.js)
        run: npm run build

      # Аутентификация в GCP по ключу сервис-аккаунта (JSON целиком хранится в секрете GCP_SA_KEY_JSON)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      # Включаем webframeworks, чтобы Firebase корректно деплоил Next.js
      - name: Enable Firebase webframeworks
        run: firebase experiments:enable webframeworks

      # Сам деплой. ВАЖНО: без --site и без target — CLI возьмет site из firebase.json
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID"
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}

      # Чистка после аутентификации (best practice)
      - name: Post Authenticate to Google Cloud
        if: always()
        run: echo "Cleanup handled by action"
